// Code generated by SQLBoiler 4.1.1 (https://github.com/volatiletech/sqlboiler/v4). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testBankDeposits(t *testing.T) {
	t.Parallel()

	query := BankDeposits()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testBankDepositsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &BankDeposit{}
	if err = randomize.Struct(seed, o, bankDepositDBTypes, true, bankDepositColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BankDeposit struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := BankDeposits().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testBankDepositsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &BankDeposit{}
	if err = randomize.Struct(seed, o, bankDepositDBTypes, true, bankDepositColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BankDeposit struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := BankDeposits().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := BankDeposits().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testBankDepositsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &BankDeposit{}
	if err = randomize.Struct(seed, o, bankDepositDBTypes, true, bankDepositColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BankDeposit struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := BankDepositSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := BankDeposits().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testBankDepositsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &BankDeposit{}
	if err = randomize.Struct(seed, o, bankDepositDBTypes, true, bankDepositColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BankDeposit struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := BankDepositExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if BankDeposit exists: %s", err)
	}
	if !e {
		t.Errorf("Expected BankDepositExists to return true, but got false.")
	}
}

func testBankDepositsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &BankDeposit{}
	if err = randomize.Struct(seed, o, bankDepositDBTypes, true, bankDepositColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BankDeposit struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	bankDepositFound, err := FindBankDeposit(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if bankDepositFound == nil {
		t.Error("want a record, got nil")
	}
}

func testBankDepositsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &BankDeposit{}
	if err = randomize.Struct(seed, o, bankDepositDBTypes, true, bankDepositColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BankDeposit struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = BankDeposits().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testBankDepositsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &BankDeposit{}
	if err = randomize.Struct(seed, o, bankDepositDBTypes, true, bankDepositColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BankDeposit struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := BankDeposits().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testBankDepositsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	bankDepositOne := &BankDeposit{}
	bankDepositTwo := &BankDeposit{}
	if err = randomize.Struct(seed, bankDepositOne, bankDepositDBTypes, false, bankDepositColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BankDeposit struct: %s", err)
	}
	if err = randomize.Struct(seed, bankDepositTwo, bankDepositDBTypes, false, bankDepositColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BankDeposit struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = bankDepositOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = bankDepositTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := BankDeposits().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testBankDepositsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	bankDepositOne := &BankDeposit{}
	bankDepositTwo := &BankDeposit{}
	if err = randomize.Struct(seed, bankDepositOne, bankDepositDBTypes, false, bankDepositColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BankDeposit struct: %s", err)
	}
	if err = randomize.Struct(seed, bankDepositTwo, bankDepositDBTypes, false, bankDepositColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BankDeposit struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = bankDepositOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = bankDepositTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := BankDeposits().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func testBankDepositsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &BankDeposit{}
	if err = randomize.Struct(seed, o, bankDepositDBTypes, true, bankDepositColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BankDeposit struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := BankDeposits().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testBankDepositsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &BankDeposit{}
	if err = randomize.Struct(seed, o, bankDepositDBTypes, true); err != nil {
		t.Errorf("Unable to randomize BankDeposit struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(bankDepositColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := BankDeposits().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testBankDepositToOneBankAccountUsingBankAccount(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local BankDeposit
	var foreign BankAccount

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, bankDepositDBTypes, false, bankDepositColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BankDeposit struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, bankAccountDBTypes, false, bankAccountColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BankAccount struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.BankAccountID = foreign.ID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.BankAccount().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.ID != foreign.ID {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	slice := BankDepositSlice{&local}
	if err = local.L.LoadBankAccount(ctx, tx, false, (*[]*BankDeposit)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.BankAccount == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.BankAccount = nil
	if err = local.L.LoadBankAccount(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.BankAccount == nil {
		t.Error("struct should have been eager loaded")
	}
}

func testBankDepositToOneSetOpBankAccountUsingBankAccount(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a BankDeposit
	var b, c BankAccount

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, bankDepositDBTypes, false, strmangle.SetComplement(bankDepositPrimaryKeyColumns, bankDepositColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, bankAccountDBTypes, false, strmangle.SetComplement(bankAccountPrimaryKeyColumns, bankAccountColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, bankAccountDBTypes, false, strmangle.SetComplement(bankAccountPrimaryKeyColumns, bankAccountColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*BankAccount{&b, &c} {
		err = a.SetBankAccount(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.BankAccount != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.BankDeposits[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.BankAccountID != x.ID {
			t.Error("foreign key was wrong value", a.BankAccountID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.BankAccountID))
		reflect.Indirect(reflect.ValueOf(&a.BankAccountID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.BankAccountID != x.ID {
			t.Error("foreign key was wrong value", a.BankAccountID, x.ID)
		}
	}
}

func testBankDepositsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &BankDeposit{}
	if err = randomize.Struct(seed, o, bankDepositDBTypes, true, bankDepositColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BankDeposit struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testBankDepositsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &BankDeposit{}
	if err = randomize.Struct(seed, o, bankDepositDBTypes, true, bankDepositColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BankDeposit struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := BankDepositSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testBankDepositsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &BankDeposit{}
	if err = randomize.Struct(seed, o, bankDepositDBTypes, true, bankDepositColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BankDeposit struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := BankDeposits().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	bankDepositDBTypes = map[string]string{`ID`: `character`, `BankAccountID`: `character`, `Amount`: `double precision`, `Date`: `bigint`}
	_                  = bytes.MinRead
)

func testBankDepositsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(bankDepositPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(bankDepositAllColumns) == len(bankDepositPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &BankDeposit{}
	if err = randomize.Struct(seed, o, bankDepositDBTypes, true, bankDepositColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BankDeposit struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := BankDeposits().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, bankDepositDBTypes, true, bankDepositPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize BankDeposit struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testBankDepositsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(bankDepositAllColumns) == len(bankDepositPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &BankDeposit{}
	if err = randomize.Struct(seed, o, bankDepositDBTypes, true, bankDepositColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BankDeposit struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := BankDeposits().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, bankDepositDBTypes, true, bankDepositPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize BankDeposit struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(bankDepositAllColumns, bankDepositPrimaryKeyColumns) {
		fields = bankDepositAllColumns
	} else {
		fields = strmangle.SetComplement(
			bankDepositAllColumns,
			bankDepositPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := BankDepositSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testBankDepositsUpsert(t *testing.T) {
	t.Parallel()

	if len(bankDepositAllColumns) == len(bankDepositPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := BankDeposit{}
	if err = randomize.Struct(seed, &o, bankDepositDBTypes, true); err != nil {
		t.Errorf("Unable to randomize BankDeposit struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert BankDeposit: %s", err)
	}

	count, err := BankDeposits().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, bankDepositDBTypes, false, bankDepositPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize BankDeposit struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert BankDeposit: %s", err)
	}

	count, err = BankDeposits().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
