// Code generated by SQLBoiler 3.7.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/randomize"
	"github.com/volatiletech/sqlboiler/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testBankAccounts(t *testing.T) {
	t.Parallel()

	query := BankAccounts()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testBankAccountsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &BankAccount{}
	if err = randomize.Struct(seed, o, bankAccountDBTypes, true, bankAccountColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BankAccount struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := BankAccounts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testBankAccountsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &BankAccount{}
	if err = randomize.Struct(seed, o, bankAccountDBTypes, true, bankAccountColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BankAccount struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := BankAccounts().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := BankAccounts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testBankAccountsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &BankAccount{}
	if err = randomize.Struct(seed, o, bankAccountDBTypes, true, bankAccountColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BankAccount struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := BankAccountSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := BankAccounts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testBankAccountsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &BankAccount{}
	if err = randomize.Struct(seed, o, bankAccountDBTypes, true, bankAccountColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BankAccount struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := BankAccountExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if BankAccount exists: %s", err)
	}
	if !e {
		t.Errorf("Expected BankAccountExists to return true, but got false.")
	}
}

func testBankAccountsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &BankAccount{}
	if err = randomize.Struct(seed, o, bankAccountDBTypes, true, bankAccountColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BankAccount struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	bankAccountFound, err := FindBankAccount(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if bankAccountFound == nil {
		t.Error("want a record, got nil")
	}
}

func testBankAccountsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &BankAccount{}
	if err = randomize.Struct(seed, o, bankAccountDBTypes, true, bankAccountColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BankAccount struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = BankAccounts().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testBankAccountsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &BankAccount{}
	if err = randomize.Struct(seed, o, bankAccountDBTypes, true, bankAccountColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BankAccount struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := BankAccounts().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testBankAccountsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	bankAccountOne := &BankAccount{}
	bankAccountTwo := &BankAccount{}
	if err = randomize.Struct(seed, bankAccountOne, bankAccountDBTypes, false, bankAccountColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BankAccount struct: %s", err)
	}
	if err = randomize.Struct(seed, bankAccountTwo, bankAccountDBTypes, false, bankAccountColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BankAccount struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = bankAccountOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = bankAccountTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := BankAccounts().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testBankAccountsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	bankAccountOne := &BankAccount{}
	bankAccountTwo := &BankAccount{}
	if err = randomize.Struct(seed, bankAccountOne, bankAccountDBTypes, false, bankAccountColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BankAccount struct: %s", err)
	}
	if err = randomize.Struct(seed, bankAccountTwo, bankAccountDBTypes, false, bankAccountColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BankAccount struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = bankAccountOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = bankAccountTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := BankAccounts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func testBankAccountsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &BankAccount{}
	if err = randomize.Struct(seed, o, bankAccountDBTypes, true, bankAccountColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BankAccount struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := BankAccounts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testBankAccountsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &BankAccount{}
	if err = randomize.Struct(seed, o, bankAccountDBTypes, true); err != nil {
		t.Errorf("Unable to randomize BankAccount struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(bankAccountColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := BankAccounts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testBankAccountToManyBankDeposits(t *testing.T) {
	var err error
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a BankAccount
	var b, c BankDeposit

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, bankAccountDBTypes, true, bankAccountColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BankAccount struct: %s", err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = randomize.Struct(seed, &b, bankDepositDBTypes, false, bankDepositColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, bankDepositDBTypes, false, bankDepositColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}

	b.BankAccountID = a.ID
	c.BankAccountID = a.ID

	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := a.BankDeposits().All(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	bFound, cFound := false, false
	for _, v := range check {
		if v.BankAccountID == b.BankAccountID {
			bFound = true
		}
		if v.BankAccountID == c.BankAccountID {
			cFound = true
		}
	}

	if !bFound {
		t.Error("expected to find b")
	}
	if !cFound {
		t.Error("expected to find c")
	}

	slice := BankAccountSlice{&a}
	if err = a.L.LoadBankDeposits(ctx, tx, false, (*[]*BankAccount)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.BankDeposits); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	a.R.BankDeposits = nil
	if err = a.L.LoadBankDeposits(ctx, tx, true, &a, nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.BankDeposits); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	if t.Failed() {
		t.Logf("%#v", check)
	}
}

func testBankAccountToManyAddOpBankDeposits(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a BankAccount
	var b, c, d, e BankDeposit

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, bankAccountDBTypes, false, strmangle.SetComplement(bankAccountPrimaryKeyColumns, bankAccountColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*BankDeposit{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, bankDepositDBTypes, false, strmangle.SetComplement(bankDepositPrimaryKeyColumns, bankDepositColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	foreignersSplitByInsertion := [][]*BankDeposit{
		{&b, &c},
		{&d, &e},
	}

	for i, x := range foreignersSplitByInsertion {
		err = a.AddBankDeposits(ctx, tx, i != 0, x...)
		if err != nil {
			t.Fatal(err)
		}

		first := x[0]
		second := x[1]

		if a.ID != first.BankAccountID {
			t.Error("foreign key was wrong value", a.ID, first.BankAccountID)
		}
		if a.ID != second.BankAccountID {
			t.Error("foreign key was wrong value", a.ID, second.BankAccountID)
		}

		if first.R.BankAccount != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}
		if second.R.BankAccount != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}

		if a.R.BankDeposits[i*2] != first {
			t.Error("relationship struct slice not set to correct value")
		}
		if a.R.BankDeposits[i*2+1] != second {
			t.Error("relationship struct slice not set to correct value")
		}

		count, err := a.BankDeposits().Count(ctx, tx)
		if err != nil {
			t.Fatal(err)
		}
		if want := int64((i + 1) * 2); count != want {
			t.Error("want", want, "got", count)
		}
	}
}

func testBankAccountsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &BankAccount{}
	if err = randomize.Struct(seed, o, bankAccountDBTypes, true, bankAccountColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BankAccount struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testBankAccountsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &BankAccount{}
	if err = randomize.Struct(seed, o, bankAccountDBTypes, true, bankAccountColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BankAccount struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := BankAccountSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testBankAccountsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &BankAccount{}
	if err = randomize.Struct(seed, o, bankAccountDBTypes, true, bankAccountColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BankAccount struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := BankAccounts().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	bankAccountDBTypes = map[string]string{`ID`: `character`, `AccountName`: `character varying`, `AccountNumber`: `character varying`, `Bank`: `character varying`}
	_                  = bytes.MinRead
)

func testBankAccountsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(bankAccountPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(bankAccountAllColumns) == len(bankAccountPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &BankAccount{}
	if err = randomize.Struct(seed, o, bankAccountDBTypes, true, bankAccountColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BankAccount struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := BankAccounts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, bankAccountDBTypes, true, bankAccountPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize BankAccount struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testBankAccountsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(bankAccountAllColumns) == len(bankAccountPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &BankAccount{}
	if err = randomize.Struct(seed, o, bankAccountDBTypes, true, bankAccountColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BankAccount struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := BankAccounts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, bankAccountDBTypes, true, bankAccountPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize BankAccount struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(bankAccountAllColumns, bankAccountPrimaryKeyColumns) {
		fields = bankAccountAllColumns
	} else {
		fields = strmangle.SetComplement(
			bankAccountAllColumns,
			bankAccountPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := BankAccountSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testBankAccountsUpsert(t *testing.T) {
	t.Parallel()

	if len(bankAccountAllColumns) == len(bankAccountPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := BankAccount{}
	if err = randomize.Struct(seed, &o, bankAccountDBTypes, true); err != nil {
		t.Errorf("Unable to randomize BankAccount struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert BankAccount: %s", err)
	}

	count, err := BankAccounts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, bankAccountDBTypes, false, bankAccountPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize BankAccount struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert BankAccount: %s", err)
	}

	count, err = BankAccounts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
