// Code generated by SQLBoiler 4.1.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Account         string
	Branch          string
	Brand           string
	Category        string
	Customer        string
	Inventory       string
	Payment         string
	Product         string
	ProductCategory string
	Sale            string
	SaleItem        string
	Transaction     string
	Users           string
}{
	Account:         "account",
	Branch:          "branch",
	Brand:           "brand",
	Category:        "category",
	Customer:        "customer",
	Inventory:       "inventory",
	Payment:         "payment",
	Product:         "product",
	ProductCategory: "product_category",
	Sale:            "sale",
	SaleItem:        "sale_item",
	Transaction:     "transaction",
	Users:           "users",
}
