// Code generated by SQLBoiler 4.1.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testDailySummaries(t *testing.T) {
	t.Parallel()

	query := DailySummaries()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testDailySummariesDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &DailySummary{}
	if err = randomize.Struct(seed, o, dailySummaryDBTypes, true, dailySummaryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DailySummary struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := DailySummaries().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testDailySummariesQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &DailySummary{}
	if err = randomize.Struct(seed, o, dailySummaryDBTypes, true, dailySummaryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DailySummary struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := DailySummaries().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := DailySummaries().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testDailySummariesSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &DailySummary{}
	if err = randomize.Struct(seed, o, dailySummaryDBTypes, true, dailySummaryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DailySummary struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := DailySummarySlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := DailySummaries().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testDailySummariesExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &DailySummary{}
	if err = randomize.Struct(seed, o, dailySummaryDBTypes, true, dailySummaryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DailySummary struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := DailySummaryExists(ctx, tx, o.Date)
	if err != nil {
		t.Errorf("Unable to check if DailySummary exists: %s", err)
	}
	if !e {
		t.Errorf("Expected DailySummaryExists to return true, but got false.")
	}
}

func testDailySummariesFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &DailySummary{}
	if err = randomize.Struct(seed, o, dailySummaryDBTypes, true, dailySummaryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DailySummary struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	dailySummaryFound, err := FindDailySummary(ctx, tx, o.Date)
	if err != nil {
		t.Error(err)
	}

	if dailySummaryFound == nil {
		t.Error("want a record, got nil")
	}
}

func testDailySummariesBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &DailySummary{}
	if err = randomize.Struct(seed, o, dailySummaryDBTypes, true, dailySummaryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DailySummary struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = DailySummaries().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testDailySummariesOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &DailySummary{}
	if err = randomize.Struct(seed, o, dailySummaryDBTypes, true, dailySummaryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DailySummary struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := DailySummaries().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testDailySummariesAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	dailySummaryOne := &DailySummary{}
	dailySummaryTwo := &DailySummary{}
	if err = randomize.Struct(seed, dailySummaryOne, dailySummaryDBTypes, false, dailySummaryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DailySummary struct: %s", err)
	}
	if err = randomize.Struct(seed, dailySummaryTwo, dailySummaryDBTypes, false, dailySummaryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DailySummary struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = dailySummaryOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = dailySummaryTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := DailySummaries().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testDailySummariesCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	dailySummaryOne := &DailySummary{}
	dailySummaryTwo := &DailySummary{}
	if err = randomize.Struct(seed, dailySummaryOne, dailySummaryDBTypes, false, dailySummaryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DailySummary struct: %s", err)
	}
	if err = randomize.Struct(seed, dailySummaryTwo, dailySummaryDBTypes, false, dailySummaryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DailySummary struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = dailySummaryOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = dailySummaryTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := DailySummaries().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func testDailySummariesInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &DailySummary{}
	if err = randomize.Struct(seed, o, dailySummaryDBTypes, true, dailySummaryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DailySummary struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := DailySummaries().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testDailySummariesInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &DailySummary{}
	if err = randomize.Struct(seed, o, dailySummaryDBTypes, true); err != nil {
		t.Errorf("Unable to randomize DailySummary struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(dailySummaryColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := DailySummaries().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testDailySummariesReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &DailySummary{}
	if err = randomize.Struct(seed, o, dailySummaryDBTypes, true, dailySummaryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DailySummary struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testDailySummariesReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &DailySummary{}
	if err = randomize.Struct(seed, o, dailySummaryDBTypes, true, dailySummaryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DailySummary struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := DailySummarySlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testDailySummariesSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &DailySummary{}
	if err = randomize.Struct(seed, o, dailySummaryDBTypes, true, dailySummaryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DailySummary struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := DailySummaries().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	dailySummaryDBTypes = map[string]string{`Income`: `double precision`, `Expenditure`: `double precision`, `BankDeposit`: `double precision`, `Date`: `bigint`}
	_                   = bytes.MinRead
)

func testDailySummariesUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(dailySummaryPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(dailySummaryAllColumns) == len(dailySummaryPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &DailySummary{}
	if err = randomize.Struct(seed, o, dailySummaryDBTypes, true, dailySummaryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DailySummary struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := DailySummaries().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, dailySummaryDBTypes, true, dailySummaryPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize DailySummary struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testDailySummariesSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(dailySummaryAllColumns) == len(dailySummaryPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &DailySummary{}
	if err = randomize.Struct(seed, o, dailySummaryDBTypes, true, dailySummaryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DailySummary struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := DailySummaries().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, dailySummaryDBTypes, true, dailySummaryPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize DailySummary struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(dailySummaryAllColumns, dailySummaryPrimaryKeyColumns) {
		fields = dailySummaryAllColumns
	} else {
		fields = strmangle.SetComplement(
			dailySummaryAllColumns,
			dailySummaryPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := DailySummarySlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testDailySummariesUpsert(t *testing.T) {
	t.Parallel()

	if len(dailySummaryAllColumns) == len(dailySummaryPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := DailySummary{}
	if err = randomize.Struct(seed, &o, dailySummaryDBTypes, true); err != nil {
		t.Errorf("Unable to randomize DailySummary struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert DailySummary: %s", err)
	}

	count, err := DailySummaries().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, dailySummaryDBTypes, false, dailySummaryPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize DailySummary struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert DailySummary: %s", err)
	}

	count, err = DailySummaries().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
