// Code generated by SQLBoiler 3.6.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("Accounts", testAccountsUpsert)

	t.Run("Branches", testBranchesUpsert)

	t.Run("Brands", testBrandsUpsert)

	t.Run("Categories", testCategoriesUpsert)

	t.Run("Customers", testCustomersUpsert)

	t.Run("Deposits", testDepositsUpsert)

	t.Run("Payments", testPaymentsUpsert)

	t.Run("Products", testProductsUpsert)

	t.Run("ProductCategories", testProductCategoriesUpsert)

	t.Run("Sales", testSalesUpsert)

	t.Run("SaleItems", testSaleItemsUpsert)

	t.Run("Stocks", testStocksUpsert)

	t.Run("Users", testUsersUpsert)

	t.Run("Withdrawals", testWithdrawalsUpsert)
}
