// Code generated by SQLBoiler 3.7.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/queries/qm"
	"github.com/volatiletech/sqlboiler/queries/qmhelper"
	"github.com/volatiletech/sqlboiler/strmangle"
)

// RepsExpense is an object representing the database table.
type RepsExpense struct {
	ID         string  `boil:"id" json:"id" toml:"id" yaml:"id"`
	SalesRepID string  `boil:"sales_rep_id" json:"sales_rep_id" toml:"sales_rep_id" yaml:"sales_rep_id"`
	Amount     float64 `boil:"amount" json:"amount" toml:"amount" yaml:"amount"`
	Reason     string  `boil:"reason" json:"reason" toml:"reason" yaml:"reason"`
	Date       int64   `boil:"date" json:"date" toml:"date" yaml:"date"`

	R *repsExpenseR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L repsExpenseL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var RepsExpenseColumns = struct {
	ID         string
	SalesRepID string
	Amount     string
	Reason     string
	Date       string
}{
	ID:         "id",
	SalesRepID: "sales_rep_id",
	Amount:     "amount",
	Reason:     "reason",
	Date:       "date",
}

// Generated where

var RepsExpenseWhere = struct {
	ID         whereHelperstring
	SalesRepID whereHelperstring
	Amount     whereHelperfloat64
	Reason     whereHelperstring
	Date       whereHelperint64
}{
	ID:         whereHelperstring{field: "\"reps_expense\".\"id\""},
	SalesRepID: whereHelperstring{field: "\"reps_expense\".\"sales_rep_id\""},
	Amount:     whereHelperfloat64{field: "\"reps_expense\".\"amount\""},
	Reason:     whereHelperstring{field: "\"reps_expense\".\"reason\""},
	Date:       whereHelperint64{field: "\"reps_expense\".\"date\""},
}

// RepsExpenseRels is where relationship names are stored.
var RepsExpenseRels = struct {
	SalesRep string
}{
	SalesRep: "SalesRep",
}

// repsExpenseR is where relationships are stored.
type repsExpenseR struct {
	SalesRep *User
}

// NewStruct creates a new relationship struct
func (*repsExpenseR) NewStruct() *repsExpenseR {
	return &repsExpenseR{}
}

// repsExpenseL is where Load methods for each relationship are stored.
type repsExpenseL struct{}

var (
	repsExpenseAllColumns            = []string{"id", "sales_rep_id", "amount", "reason", "date"}
	repsExpenseColumnsWithoutDefault = []string{"id", "sales_rep_id", "amount", "reason", "date"}
	repsExpenseColumnsWithDefault    = []string{}
	repsExpensePrimaryKeyColumns     = []string{"id"}
)

type (
	// RepsExpenseSlice is an alias for a slice of pointers to RepsExpense.
	// This should generally be used opposed to []RepsExpense.
	RepsExpenseSlice []*RepsExpense

	repsExpenseQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	repsExpenseType                 = reflect.TypeOf(&RepsExpense{})
	repsExpenseMapping              = queries.MakeStructMapping(repsExpenseType)
	repsExpensePrimaryKeyMapping, _ = queries.BindMapping(repsExpenseType, repsExpenseMapping, repsExpensePrimaryKeyColumns)
	repsExpenseInsertCacheMut       sync.RWMutex
	repsExpenseInsertCache          = make(map[string]insertCache)
	repsExpenseUpdateCacheMut       sync.RWMutex
	repsExpenseUpdateCache          = make(map[string]updateCache)
	repsExpenseUpsertCacheMut       sync.RWMutex
	repsExpenseUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

// One returns a single repsExpense record from the query.
func (q repsExpenseQuery) One(ctx context.Context, exec boil.ContextExecutor) (*RepsExpense, error) {
	o := &RepsExpense{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for reps_expense")
	}

	return o, nil
}

// All returns all RepsExpense records from the query.
func (q repsExpenseQuery) All(ctx context.Context, exec boil.ContextExecutor) (RepsExpenseSlice, error) {
	var o []*RepsExpense

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to RepsExpense slice")
	}

	return o, nil
}

// Count returns the count of all RepsExpense records in the query.
func (q repsExpenseQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count reps_expense rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q repsExpenseQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if reps_expense exists")
	}

	return count > 0, nil
}

// SalesRep pointed to by the foreign key.
func (o *RepsExpense) SalesRep(mods ...qm.QueryMod) userQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.SalesRepID),
	}

	queryMods = append(queryMods, mods...)

	query := Users(queryMods...)
	queries.SetFrom(query.Query, "\"users\"")

	return query
}

// LoadSalesRep allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (repsExpenseL) LoadSalesRep(ctx context.Context, e boil.ContextExecutor, singular bool, maybeRepsExpense interface{}, mods queries.Applicator) error {
	var slice []*RepsExpense
	var object *RepsExpense

	if singular {
		object = maybeRepsExpense.(*RepsExpense)
	} else {
		slice = *maybeRepsExpense.(*[]*RepsExpense)
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &repsExpenseR{}
		}
		args = append(args, object.SalesRepID)

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &repsExpenseR{}
			}

			for _, a := range args {
				if a == obj.SalesRepID {
					continue Outer
				}
			}

			args = append(args, obj.SalesRepID)

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(qm.From(`users`), qm.WhereIn(`users.id in ?`, args...))
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load User")
	}

	var resultSlice []*User
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice User")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for users")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for users")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.SalesRep = foreign
		if foreign.R == nil {
			foreign.R = &userR{}
		}
		foreign.R.SalesRepRepsExpenses = append(foreign.R.SalesRepRepsExpenses, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.SalesRepID == foreign.ID {
				local.R.SalesRep = foreign
				if foreign.R == nil {
					foreign.R = &userR{}
				}
				foreign.R.SalesRepRepsExpenses = append(foreign.R.SalesRepRepsExpenses, local)
				break
			}
		}
	}

	return nil
}

// SetSalesRep of the repsExpense to the related item.
// Sets o.R.SalesRep to related.
// Adds o to related.R.SalesRepRepsExpenses.
func (o *RepsExpense) SetSalesRep(ctx context.Context, exec boil.ContextExecutor, insert bool, related *User) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"reps_expense\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"sales_rep_id"}),
		strmangle.WhereClause("\"", "\"", 2, repsExpensePrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.SalesRepID = related.ID
	if o.R == nil {
		o.R = &repsExpenseR{
			SalesRep: related,
		}
	} else {
		o.R.SalesRep = related
	}

	if related.R == nil {
		related.R = &userR{
			SalesRepRepsExpenses: RepsExpenseSlice{o},
		}
	} else {
		related.R.SalesRepRepsExpenses = append(related.R.SalesRepRepsExpenses, o)
	}

	return nil
}

// RepsExpenses retrieves all the records using an executor.
func RepsExpenses(mods ...qm.QueryMod) repsExpenseQuery {
	mods = append(mods, qm.From("\"reps_expense\""))
	return repsExpenseQuery{NewQuery(mods...)}
}

// FindRepsExpense retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindRepsExpense(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) (*RepsExpense, error) {
	repsExpenseObj := &RepsExpense{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"reps_expense\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, repsExpenseObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from reps_expense")
	}

	return repsExpenseObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *RepsExpense) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no reps_expense provided for insertion")
	}

	var err error

	nzDefaults := queries.NonZeroDefaultSet(repsExpenseColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	repsExpenseInsertCacheMut.RLock()
	cache, cached := repsExpenseInsertCache[key]
	repsExpenseInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			repsExpenseAllColumns,
			repsExpenseColumnsWithDefault,
			repsExpenseColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(repsExpenseType, repsExpenseMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(repsExpenseType, repsExpenseMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"reps_expense\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"reps_expense\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into reps_expense")
	}

	if !cached {
		repsExpenseInsertCacheMut.Lock()
		repsExpenseInsertCache[key] = cache
		repsExpenseInsertCacheMut.Unlock()
	}

	return nil
}

// Update uses an executor to update the RepsExpense.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *RepsExpense) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	key := makeCacheKey(columns, nil)
	repsExpenseUpdateCacheMut.RLock()
	cache, cached := repsExpenseUpdateCache[key]
	repsExpenseUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			repsExpenseAllColumns,
			repsExpensePrimaryKeyColumns,
		)

		if len(wl) == 0 {
			return 0, errors.New("models: unable to update reps_expense, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"reps_expense\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, repsExpensePrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(repsExpenseType, repsExpenseMapping, append(wl, repsExpensePrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update reps_expense row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for reps_expense")
	}

	if !cached {
		repsExpenseUpdateCacheMut.Lock()
		repsExpenseUpdateCache[key] = cache
		repsExpenseUpdateCacheMut.Unlock()
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values.
func (q repsExpenseQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for reps_expense")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for reps_expense")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o RepsExpenseSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), repsExpensePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"reps_expense\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, repsExpensePrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in repsExpense slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all repsExpense")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *RepsExpense) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no reps_expense provided for upsert")
	}

	nzDefaults := queries.NonZeroDefaultSet(repsExpenseColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	repsExpenseUpsertCacheMut.RLock()
	cache, cached := repsExpenseUpsertCache[key]
	repsExpenseUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			repsExpenseAllColumns,
			repsExpenseColumnsWithDefault,
			repsExpenseColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			repsExpenseAllColumns,
			repsExpensePrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert reps_expense, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(repsExpensePrimaryKeyColumns))
			copy(conflict, repsExpensePrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"reps_expense\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(repsExpenseType, repsExpenseMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(repsExpenseType, repsExpenseMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if err == sql.ErrNoRows {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert reps_expense")
	}

	if !cached {
		repsExpenseUpsertCacheMut.Lock()
		repsExpenseUpsertCache[key] = cache
		repsExpenseUpsertCacheMut.Unlock()
	}

	return nil
}

// Delete deletes a single RepsExpense record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *RepsExpense) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no RepsExpense provided for delete")
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), repsExpensePrimaryKeyMapping)
	sql := "DELETE FROM \"reps_expense\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from reps_expense")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for reps_expense")
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q repsExpenseQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no repsExpenseQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from reps_expense")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for reps_expense")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o RepsExpenseSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), repsExpensePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"reps_expense\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, repsExpensePrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from repsExpense slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for reps_expense")
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *RepsExpense) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindRepsExpense(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *RepsExpenseSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := RepsExpenseSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), repsExpensePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"reps_expense\".* FROM \"reps_expense\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, repsExpensePrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in RepsExpenseSlice")
	}

	*o = slice

	return nil
}

// RepsExpenseExists checks if the RepsExpense row exists.
func RepsExpenseExists(ctx context.Context, exec boil.ContextExecutor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"reps_expense\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if reps_expense exists")
	}

	return exists, nil
}
