[psql]
    dbname = "shared"
    host = "localhost"
    port = "5433"
    user = "postgres"
    pass = "postgres"
    sslmode = "disable"
    whitelist=[
            "branch",
            "users",
            "customer",
            "account",
            "transaction",
            "brand",
            "category",
            "product",
            "product_category",
            "stock",
            "sale",
            "sale_item",
            "payment",
            ]
