[psql]
    dbname = "shared"
    host = "localhost"
    port = "5433"
    user = "postgres"
    pass = "postgres"
    sslmode = "disable"
    whitelist=[
            "branch",
            "users",
            "customer",
            "account",
            "transaction",
            "brand",
            "category",
            "product",
            "product_category",
            "inventory",
            "sale",
            "sale_item",
            "payment",
	    "bank_account",
	    "bank_deposit",
	    "expenditure",
	    "daily_summary",
        "ds_commission",
        "reps_expense"
            ]
